spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # set @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    url: jdbc:mysql://127.0.0.1:3306/
    username:
    password:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 100000MB

#  error:
#    include-stacktrace: never
#    whitelabel:
#      enabled: false
server:
  port: 8096


# 选择api项目下的resouces路径下的user文件夹
# filePath: "/Users/yangyida/Documents/project/complaint_system/web-server/src/main/resources/img/user/"
filePath: "D:/Desktop/System/history/Community/Community-system/core/src/main/resources/img/user/"
#D:\Desktop\System\history\Community\Community-system\core\src\main\resources
# 服务器url路径
projecturl: "http://192.168.0.211:8096"


